$(document).ready(function() {
  // Block#: 1
  function on_Button_click(e) {
    try {
      // Block#: 2
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", 'Ecco la label');
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 812183-288603-232736-481468
